In [11]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
x = np.zeros(10 ,dtype = int)
x[4]=1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [19]:
# 2. Create a vector with values ranging from 10 to 49.

x = np.arange(10,50)
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8.

x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0].

A = [1,2,0,0,4,0]
B = []

for i in range(len(A)):
    if A[i] != 0:
        B.append(A[i])
        
print(B)

[1, 2, 4]


In [27]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

x = np.random.random((10,10))
print(x) 
xmin = x.min() 
xmax = x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.03196527 0.22005591 0.44437444 0.89491531 0.83407819 0.86114413
  0.00741453 0.37331755 0.00648504 0.61999982]
 [0.68234311 0.45605285 0.70305121 0.87532536 0.01889902 0.16850151
  0.92700492 0.03494069 0.64891598 0.00841631]
 [0.29640486 0.19958385 0.05971277 0.83523829 0.40569656 0.27309265
  0.8001524  0.8197386  0.53613967 0.89675291]
 [0.8436187  0.77824441 0.46874311 0.25409264 0.72734854 0.81419075
  0.03614347 0.31667395 0.75783421 0.84442095]
 [0.56074115 0.60247884 0.38358506 0.7552057  0.49403998 0.44027835
  0.79309869 0.50033311 0.03887527 0.25937025]
 [0.9771977  0.10394556 0.56818204 0.39889597 0.59320312 0.37542223
  0.16060423 0.25362191 0.59865826 0.41747425]
 [0.65836224 0.70888007 0.62169232 0.82434601 0.06328364 0.51224482
  0.25745891 0.68967993 0.90743351 0.36755189]
 [0.70509958 0.24026549 0.6956542  0.41410544 0.8677414  0.6625575
  0.80018485 0.50748003 0.49641563 0.20610011]
 [0.10907817 0.25070026 0.33828883 0.85929275 0.52236906 0.20954666
  0.58763427 

In [31]:
# 6. Create a random vector of size 30 and find the mean value.
    
x = np.random.random((30))
mean=np.mean(x)
print(mean)


0.467588772353736
